tags: ['language:typescript','framework:angular']
files:
  README.md.twig: {}

  App/Api/Api.ts.twig:
      overwrite: false
      fileName: "App/Api/Api{{ tag|class_name }}.ts"
      forPathExpression:
        key: tag
        expression: swagger.paths.*.get.tags[0] || swagger.paths.*.put.tags[0] || swagger.paths.*.delete.tags[0] || swagger.paths.*.post.tags[0]

  App/BaseApi/BaseApi.ts.twig:
      #overwrite: false
      fileName: "App/BaseApi/BaseApi{{ tag|class_name }}.ts"
      forPathExpression:
        key: tag
        expression: swagger.paths.*.get.tags[0] || swagger.paths.*.put.tags[0] || swagger.paths.*.delete.tags[0] || swagger.paths.*.post.tags[0]

  App/BaseModel/model.ts.twig:
      fileName: "App/BaseModel/Base{{ definitionName|class_name }}.ts"
      for:
        key: definitionName
        value: schema
        in:  '[swagger].definitions'

  App/Model/model.ts.twig:
      overwrite: false
      fileName: "App/Model/{{ definitionName|class_name }}.ts"
      for:
        key: definitionName
        value: schema
        in:  '[swagger].definitions'

  App/Model/models.ts.twig:
      fileName: "App/Model/models.ts"

  App/Api/Apis.ts.twig:
      fileName: "App/Api/apis.ts"
      with:
          tags:
              pathExpression: swagger.paths.*.get.tags[0] || swagger.paths.*.put.tags[0] || swagger.paths.*.delete.tags[0] || swagger.paths.*.post.tags[0]
              unique: true
      #overwrite: false
  App/AppHttp.ts.twig: {}
      #overwrite: false